version: "3.7"

services:

    php:
        container_name: php
        image: viblo:backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: viblo_dbs
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
            - backend

    nginx:
        image: nginx:1.25.1
        container_name: nginx
        volumes:
            - ./backend:/var/www/html/backend
            - ./frontend:/var/www/html/frontend
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/log/:/var/log/nginx
        depends_on:
            - php
            - mysql
        ports:
            - 80:80
        networks:
            - backend
            - frontend

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        # restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - backend

    node:
        container_name: nodejs
        image: viblo:frontend
        stdin_open: true
        # restart: always
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/app
        networks:
            - frontend
    minio:
        image: minio/minio
        container_name: c-minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./docker/minio:/data
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: 123hiep123
        command: server --console-address ":9001" /data
        networks:
            - backend
networks:
    backend:
    frontend:
